easy_admin:
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'email' }
                    - { property: 'password', type: 'password', type_options: { mapped: true } }
